### ISSUE TITLE
can you recommend some link to learn VW regression/classification by examples

### ISSUE THREAD

**Issue by Sandy4321** [jakac/subwabbit#5]
For Kaggle playing use official vowpalwabbit package, for production use subwabbit

can you recommend some link to learn VW regression/classification by examples 
for example how to make interactions for categorical features only , not for continues features

**Comment by jakac** [comment]
Hi, there is an example for how to use subwabbit for both continuous and categorical features in the [README](https://github.com/jakac/subwabbit#example-use), e.g. `|b item123` is a categorical feature in a namespace `b`. To learn interactions between namespaces, let's say `a` and `b`, just use `-q ab` argument to `vw`, for example for training line like `1 |a categorical1 categotical2 |b categorical3 categorical4`, it will learn following interactions:
- categorical1*categorical3
- categorical1*categorical4
- categorical2*categorical3
- categorical2*categorical4

vw assumes that feature value is equal to 1.0 for categorical features.

You can use logistic regression for classification instead of linear regression also by command line arguments to `vw` command passed as a second argument to `VowpalWabbitProcess` constructor.
